import { exportPatientsToExcel } from './utils/exportPatientsToExcel.js';

// Test data with medications array
const testData = [
   {
    id: 4,
    user_id: 1,
    response_data: {
      bp: '64',
      age: '45',
      bmi: '23.03',
      hip: '7',
      ihd: 'Yes',
      leak: '5',
      name: 'Lakshmi S',
      neck: '13',
      spo2: '97',
      email: 'lakshmi@gmail.com',
      phone: '9990005196',
      waist: '22',
      gender: 'F',
      height: '168',
      iss_q1: 'No',
      iss_q3: 'Yes',
      iss_q4: 'No',
      iss_q5: 'Yes',
      iss_q6: 'No',
      iss_q7: 'Yes',
      scores: [Object],
      stroke: 'No',
      weight: '65',
      bedtime: '22:30',
      bruxism: 'N',
      iss_q2a: 'No',
      iss_q8a: 'No',
      iss_q8b: 'Yes',
      iss_q8c: 'No',
      iss_q8d: 'Yes',
      iss_q8e: 'No',
      p90_p95: '1',
      snoring: 'Y',
      diabetes: 'No',
      mask_fit: 'Good',
      pap_mode: 'APAP',
      cpap_days: '1.99',
      ess_score: '12',
      iss_score: '11',
      mask_type: 'Oronasal',
      mallampati: '3',
      narcolepsy: 'N',
      occupation: 'Teacher',
      hospital_id: 'H001',
      medications: [Array],
      parasomnias: 'Y',
      avg_duration: '10',
      hypertension: 'No',
      rem_disorder: 'Y',
      residual_ahi: '12',
      shift_worker: 'No',
      epworth_score: '10',
      followup_date: '2024-07-21',
      restless_legs: 'N',
      sleep_latency: '15-30 min',
      hypothyroidism: 'No',
      avg_sleep_hours: '7',
      iss_total_score: '10',
      waist_hip_ratio: '3.14',
      night_awakenings: '>2 times',
      witnessed_apneas: 'N',
      nocturnal_choking: 'Y',
      pap_complications: 'idk',
      daytime_sleepiness: 'N',
      recommended_workup: [Array],
      clinical_impression: 'Poor Sleep',
      surgery_sleep_apnea: 'No',
      respiratory_disorder: [Array],
      difficulty_initiating: 'N',
      neurological_disorder: [Array],
      difficulty_maintaining: 'N'
    },
   

  },
];

console.log('Testing Excel export with new format...');
exportPatientsToExcel(testData, 'test-output-new.xlsx');
console.log('Export completed. Check test-output-new.xlsx file.');