// Define the exact order of columns for Excel export
export const EXCEL_COLUMN_ORDER = [
  "Hospital_ID",
  "Name",
  "Gender",
  "Age (years)",
  "Occupation",
  "Phone number",
  "e-mail ID",
  "Presenting Complaints",
  "Bedtime",
  "Sleep_latency (mins)",
  "Awakenings",
  "Sleep_hours",
  "Shift_work",
  "Shift_pattern",
  "Initiation_problem",
  "Maintenance_problem",
  "Daytime_sleepiness",
  "Snoring",
  "Witnessed_apnea",
  "Choking_spells",
  "RLS",
  "Parasomnias",
  "Parasomnia_Symptoms",
  "Narcolepsy",
  "Narcolepsy_Symptoms",
  "RBD",
  "Bruxism",
  "Hypertension",
  "Diabetes",
  "IHD",
  "Stroke",
  "Hypothyroidism",
  "Neurological_disorder",
  "Chronic_respiratory_disorder",
  "Sleep Apnea Surgery",
  "Type of Surgery",
  "Sedative_hypnotics",
  "Antidepressants",
  "Antipsychotics",
  "Stimulants",
  "Opioids",
  "Other Medications",
  "Height (m)",
  "Weight (kgs)",
  "BMI (kg/m2)",
  "Waist_circumference (cms)",
  "Hip_circumference (cms)",
  "WHR (AQ/AR)",
  "Neck_circumference (cms)",
  "SBP (mmHg)",
  "DBP (mmHg)",
  "SpO2 (%)",
  "Mallampati_grade",
  "ESS",
  "ISS",
  "Diagnosis",
  "Other Diagnosis",
  "Recommendation",
];

// Map question IDs to Excel column names
export const QUESTION_ID_TO_COLUMN_MAP = {
  // Database fields mapping (exact field names from the actual data)
  hospital_id: "Hospital_ID",
  name: "Name",
  gender: "Gender",
  age: "Age (years)",
  occupation: "Occupation",
  phone: "Phone number",
  email: "e-mail ID",
  presenting_complaints: "Presenting Complaints",
  bedtime: "Bedtime",
  sleep_latency: "Sleep_latency (mins)",
  night_awakenings: "Awakenings",
  avg_sleep_hours: "Sleep_hours",
  shift_worker: "Shift_work",
  shift_pattern: "Shift_pattern",
  difficulty_initiating: "Initiation_problem",
  difficulty_maintaining: "Maintenance_problem",
  daytime_sleepiness: "Daytime_sleepiness",
  snoring: "Snoring",
  witnessed_apneas: "Witnessed_apnea",
  nocturnal_choking: "Choking_spells",
  restless_legs: "RLS",
  parasomnias: "Parasomnias",
  parasomnia_details: "Parasomnia_Symptoms",
  narcolepsy: "Narcolepsy",
  narcolepsy_details: "Narcolepsy_Symptoms",
  rem_disorder: "RBD",
  bruxism: "Bruxism",
  hypertension: "Hypertension",
  diabetes: "Diabetes",
  ihd: "IHD",
  stroke: "Stroke",
  hypothyroidism: "Hypothyroidism",
  neurological_disorder: "Neurological_disorder",
  respiratory_disorder: "Chronic_respiratory_disorder",
  surgery_sleep_apnea: "Sleep Apnea Surgery",
  surgery_type: "Type of Surgery",
  height: "Height (m)",
  weight: "Weight (kgs)",
  bmi: "BMI (kg/m2)",
  waist: "Waist_circumference (cms)",
  hip: "Hip_circumference (cms)",
  waist_hip_ratio: "WHR (AQ/AR)",
  neck: "Neck_circumference (cms)",
  bp: "SBP (mmHg)", // Will be split in handleSpecialCases
  spo2: "SpO2 (%)",
  mallampati: "Mallampati_grade",
  ess_score: "ESS", // legacy flat
  epworth_score: "ESS", // current flat in your sample
  ess: "ESS", // flat computed
  epworthScore: "ESS", // camelCase flat
  "scores.epworthScore": "ESS", // nested
  iss: "ISS",
  iss_score: "ISS", // legacy flat
  // flat computed
  issScore: "ISS", // camelCase flat
  "scores.issScore": "ISS", // nested
  clinical_impression: "Diagnosis",
  clinical_impression_other: "Other Diagnosis",
  recommended_workup: "Recommendation",

  // Original questionnaire field mappings (for backwards compatibility)
  hospitalId: "Hospital_ID",
  patientName: "Name",
  phoneNumber: "Phone number",
  emailAddress: "e-mail ID",
  sleepLatency: "Sleep_latency (mins)",
  nightAwakenings: "Awakenings",
  sleepHours: "Sleep_hours",
  shiftWork: "Shift_work",
  shiftPattern: "Shift_pattern",
  sleepInitiation: "Initiation_problem",
  sleepMaintenance: "Maintenance_problem",
  witnessedApnea: "Witnessed_apnea",
  chokingSpells: "Choking_spells",
  rls: "RLS",
  rbd: "RBD",
  neurologicalDisorder: "Neurological_disorder",
  chronicRespiratoryDisorder: "Chronic_respiratory_disorder",
  upperAirwaySurgery: "Upper_airway_Surgery",
  sedativeHypnotics: "Sedative_hypnotics",
  antidepressants: "Antidepressants",
  antipsychotics: "Antipsychotics",
  stimulants: "Stimulants",
  opioids: "Opioids",
  medications_other: "Other Medications",
  waistCircumference: "Waist_circumference (cms)",
  hipCircumference: "Hip_circumference (cms)",
  whr: "WHR (AQ/AR)",
  neckCircumference: "Neck_circumference (cms)",
  systolicBP: "SBP (mmHg)",
  diastolicBP: "DBP (mmHg)",
  mallampatiGrade: "Mallampati_grade",
  ess_score: "ESS",
  iss_score: "ISS",
  diagnosis: "Diagnosis",
  clinical_impression_other: "Other Diagnosis",
  recommendation: "Recommendation",
};
